apiVersion: batch/v1
kind: Job
metadata:
  name: before
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: palakollu145/helloworld:purple
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
