apiVersion: batch/v1
kind: Job
metadata:
  name: gitops-{{ randAlphaNum 8 | lower }}
  annotations:
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: palakollu145/helloworld:blue
        command: ["sleep", "30"]
        # command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi({{ .Values.decimal }})"]
      restartPolicy: Never
  backoffLimit: 0
