apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    # argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 1
  template:
    spec:
      containers:
      - name: sleep
        image: {{ .Values.repository}}/{{ .Values.image }}:{{ .Values.tag }}
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
