apiVersion: batch/v1
kind: Job
metadata:
  name: gitops-{{ randAlphaNum 8 | lower }}
  annotations:
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: {{ .Values.repository}}/{{ .Values.image }}:{{ .Values.tag }}
        command: ["sleep", "30"]
      restartPolicy: Never
  backoffLimit: 0
