{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}-{{ .tag }}
  annotations:
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: sleep
        image: {{ .repository}}/{{ .image }}:{{ .tag }}
        command: ["sleep", "60"]
      restartPolicy: Never
  backoffLimit: 0
{{- end }}
