apiVersion: batch/v1
kind: Job
metadata:
  name: gitops-{{ randAlphaNum 8 | lower }}
  annotations:
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi({{ .Values.decimal }})", "sleep" ,"30"]
      restartPolicy: Never
  backoffLimit: 0
